### ISSUE TITLE
Simultaneously entering into two states when using the statemachine pub package?

### ISSUE THREAD

**Issue by nawafnaim** [renggli/dart-statemachine#1]
I have asked [this question] (http://stackoverflow.com/questions/28678903/simultaneously-entering-into-two-states-when-using-the-statemachine-pub-package) on stackoverflow:

> I have this use-case where I need the state machine to remain in a general state while switching between smaller, more specific states. Is this possible using the statemachine pub package?

**Comment by renggli** [comment]
I've tried to answer your question on StackOverflow. I'll keep this message as a feature request to add first-class composition of stack machines.

**Comment by renggli** [comment]
Added the possibility to nest machines in 888edfb.

**Comment by nawafnaim** [comment]
@renggli thank you for the quick update. 

BTW, the repo is missing transition_nested.dart.

**Comment by renggli** [comment]
Sorry, missed to add the new file. It should work again.
