### ISSUE TITLE
Why 1.5 is aligned on bleeding edge?

### ISSUE THREAD

**Issue by ohenley** [renggli/dart-statemachine#3]
Why did your latest release, 1.5, is aligned with (Dart 2.2 => flutter channel master or flutter channel dev)... both being bleeding edge? Thx.

**Comment by ohenley** [comment]
sorry, did not figure it was not meant to be used with flutter. closing.

**Comment by renggli** [comment]
AFAIK the package works with Flutter (see the tag on https://pub.dartlang.org/packages/statemachine). Also, my Flutter installation uses Dart 2.2.1.

**Comment by ohenley** [comment]
1. When I include your package in any of my flutter .dart file, I get a flood of errors... It looks like a conflict between the ubiquitous flutter State<T> type your State type. I did not check further, I was not interested in moving from 'flutter stable' 

2. From what I understand, Dart 2.2.x for flutter is only available if you choose the 'flutter dev' or 'flutter master' channel; both of which looking at their name, are unstable endeavors. Anyone aligned on production code, 'flutter stable', can't bring in your package easily.

It would be great to know which version can be brought in for 'stable'

Thx.

**Comment by renggli** [comment]
Ahh ok, looks like I am using flutter dev. You can try an older version, but shouldn't pub anyway pick a version that works with your SDK?

In any case this library has been using a class named `State` forever, I  suggest you use a prefix import or hide the class: https://www.dartlang.org/guides/language/language-tour#using-libraries
