### ISSUE TITLE
causes errors in stateful widget Flutter 

### ISSUE THREAD

**Issue by stonekase** [renggli/dart-statemachine#4]
The library causes errors if imported in a stateful widget.
This might be due to collision of name "State"

**Comment by renggli** [comment]
Can you provide more details: a stack trace of the error, and a minimal flutter application reproducing the problem?

**Comment by stonekase** [comment]
i forked it and changed the State class from State to GameState(using it in a game) and everything works fine . So i was right

**Comment by stonekase** [comment]
> Can you provide more details: a stack trace of the error, and a minimal flutter application reproducing the problem?

Flutter has a reserved name "State"

**Comment by stonekase** [comment]
> Can you provide more details: a stack trace of the error, and a minimal flutter application reproducing the problem?

<img width="615" alt="Screenshot 2020-08-15 at 20 05 02" src="https://user-images.githubusercontent.com/5037778/90319753-e0237380-df32-11ea-9765-12eae7dd74ba.png">

**Comment by renggli** [comment]
Ahh, why don't you then just alias the import of this library or Flutter, or hide the unwanted `State` class?

```dart
import 'package:statemachine/statemachine.dart' as sm;
```

**Comment by renggli** [comment]
See the language tour on how to import libraries: https://dart.dev/guides/language/language-tour#using-libraries
