### ISSUE TITLE
Integration with enums

### ISSUE THREAD

**Issue by venkatd** [renggli/dart-statemachine#5]
Hi! I have been improving the reliability of our mobile app connection, and realized that using a state machine could significantly simplify our code. There are several state machine libs out there, but this library looks very minimal which I like.

Are there any recommendations on how to integrate enums with states? As a basic example, I have the following code that exposes a `StateNotifier` (it's like a `ValueListenable` in Flutter):

(I have more complex scenarios but feel like it'll be easier to discuss something simpler first.)

```dart
import 'package:flutter/widgets.dart';
import 'package:turtle_chat/util/scheduler.dart';

import 'app_lifecycle_state.dart' as util;
import 'observable_value.dart';

class AppLifecycleStateNotifier extends ObservableValue<util.AppLifecycleState>
    with WidgetsBindingObserver {
  AppLifecycleStateNotifier({
    this.inactiveThreshold = const Duration(seconds: 30),
  }) : super(util.AppLifecycleState.resumed) {
    WidgetsBinding.instance.addObserver(this);
  }

  final Duration inactiveThreshold;
  final _inactiveScheduler = Scheduler();

  void dispose() {
    super.dispose();
    _inactiveScheduler.cancel();
    WidgetsBinding.instance.removeObserver(this);
  }

  util.AppLifecycleState get value => state;

  @override
  void didChangeAppLifecycleState(AppLifecycleState newState) {
    value = _toAppLifecycleState(newState);
    if (value == util.AppLifecycleState.paused) {
      _inactiveScheduler.runIn(
        inactiveThreshold,
        () => value = util.AppLifecycleState.pausedAndInactive,
      );
    } else {
      _inactiveScheduler.cancel();
    }
  }
}

// In order to keep our connection logic decoupled from Flutter we maintain a
// copy of AppLifecycleState.
util.AppLifecycleState _toAppLifecycleState(AppLifecycleState state) {
  switch (state) {
    case AppLifecycleState.resumed:
      return util.AppLifecycleState.resumed;
    case AppLifecycleState.inactive:
      return util.AppLifecycleState.inactive;
    case AppLifecycleState.paused:
      return util.AppLifecycleState.paused;
    case AppLifecycleState.detached:
      return util.AppLifecycleState.detached;
  }
  return util.AppLifecycleState.resumed;
}
```

I think this could be re-implemented with a `StateMachine` class with `onEntry`, `onExit`, and `onTimeout`, but I would still like to expose an enum of the current lifecycle state as part of the public interface.

I guess I could maintain a map of `<AppLifecycleState, State>`. Or I wonder if it'd make sense to allow states in the library to be generic and hold a value. As in `State<T>`?

Any thoughts? Thanks!

**Comment by renggli** [comment]
Probably easiest would be to add an `onEntry` callback to each `State` that updates a variable with the current enum value. Personally I've mostly use the state objects as the enum values, but I see that when integrating with existing code this might not be ideal. One way of making the `State` more generic would be to replace the name with a typed object?

**Comment by venkatd** [comment]
Yes as you mention, the goal is one of integration. It would be ideal for other parts of the app to have access to an enum. For example, we have a `PhoenixWebSocket` class with a `connectionState` enum property in our Flutter app. Several parts of the UI use this enum to render the UI differently based on this value (showing a connection indicator, disabling the send button, etc).

I'll give that a try this week and post back here what I come up with.

Re: generic state, are you referring to the following declaration in State?

```dart
  /// A human readable name of the state.
  final String name;
```

Thanks

**Comment by renggli** [comment]
Yeah, the idea would be to replace `name` with an arbitrary typed object (existing users could continue to use a string). However, then I imagine people would also like to set the state using these objects; which yields a strange duality between this object and the state? So probably it is easier and more flexible is if the user maintains their own mapping between some object and the states (i.e. using a [BiMap](https://github.com/renggli/dart-more/blob/master/lib/src/collection/bimap.dart))?

**Comment by venkatd** [comment]
This sounds like the way to go. Thanks for the feedback.

**Comment by renggli** [comment]
Reopening this issue to make this simpler (support of arbitrary identifier objects for states).
